name: licensor
version: 0.3.0

synopsis: A license compatibility helper
description: A license compatibility helper.

category: Distribution

stability: Experimental
github: jpvillaisaza/licensor
homepage: https://jpvillaisaza.co/licensor

author: Juan Pedro Villa Isaza <jpvillaisaza@gmail.com>
maintainer: Juan Pedro Villa Isaza <jpvillaisaza@gmail.com>
copyright: 2016 Juan Pedro Villa Isaza

license-file: LICENSE.md

extra-source-files:
  - CHANGELOG.md
  - README.md

dependencies:
  - Cabal >= 1.22 && < 2.1
  - base >= 4.8 && < 4.11
  - containers
  - directory

ghc-options:
  - -Wall

library:
  source-dirs:
    src
  dependencies:
    - process

executable:
  source-dirs:
    app
  main:
    Main.hs
  dependencies:
    - cmdargs >= 0.10 && < 0.11
    - licensor
  ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
